# Generated by Django 3.0.8 on 2020-07-17 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(max_length=1024, verbose_name='Description')),
                ('price_range', models.IntegerField(default=0)),
                ('rating', models.IntegerField(verbose_name='customer rating')),
                ('main_image', models.ImageField(default=None, upload_to='uploads/')),
                ('dance_type', models.TextField(choices=[('BALLET', 'Ballet'), ('TAP', 'Tap'), ('JAZZ', 'Jazz'), ('MODERN', 'Modern'), ('LYRICAL', 'Lyrical'), ('HIP_HOP', 'Hip Hop'), ('CONTEMPORARY', 'Contemporary'), ('FOLK', 'Folk')])),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Florist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(max_length=1024, verbose_name='Description')),
                ('price_range', models.IntegerField(default=0)),
                ('rating', models.IntegerField(verbose_name='customer rating')),
                ('main_image', models.ImageField(default=None, upload_to='uploads/')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(max_length=1024, verbose_name='Description')),
                ('price_range', models.IntegerField(default=0)),
                ('rating', models.IntegerField(verbose_name='customer rating')),
                ('main_image', models.ImageField(default=None, upload_to='uploads/')),
                ('musician', models.CharField(choices=[('BAND', 'Band'), ('DJ', 'Dj'), ('SINGER', 'Singer'), ('ORCHESTRA', 'Orchestra'), ('PIANIST', 'Pianist'), ('VIOLONIST', 'Violonist'), ('PERCUSSIONIST', 'Percussionist'), ('OTHER', 'Other')], max_length=512)),
                ('genre', models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('HIP HOP', 'Hip hop'), ('MANELE', 'Manele'), ('EDM', 'EDM'), ('CLASSICAL', 'Classical'), ('BLUES', 'Blues'), ('JAZZ', 'Jazz'), ('RNB', 'RnB'), ('FOLK', 'Folk'), ('INDIE', 'Indie'), ('OTHER', 'Other')], max_length=512)),
                ('musician_num', models.IntegerField(default=1, verbose_name='Number of musicians')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(max_length=1024, verbose_name='Description')),
                ('price_range', models.IntegerField(default=0)),
                ('rating', models.IntegerField(verbose_name='customer rating')),
                ('main_image', models.ImageField(default=None, upload_to='uploads/')),
                ('cuisine', models.TextField(verbose_name='type of food')),
                ('max_seats', models.PositiveIntegerField(verbose_name='Seats available')),
                ('ballroom', models.BooleanField(verbose_name='Has wedding ballroom')),
                ('is_chain', models.BooleanField()),
                ('has_food_sample', models.BooleanField()),
                ('has_parking', models.BooleanField(verbose_name='Restaurant parking')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('restaurant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MusicianImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('musician', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.Musician')),
            ],
        ),
        migrations.CreateModel(
            name='FloristImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('florist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.Florist')),
            ],
        ),
        migrations.CreateModel(
            name='DancerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('dancer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.Dancer')),
            ],
        ),
    ]
