# Generated by Django 3.0.8 on 2020-07-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=512)),
                ('last_name', models.CharField(max_length=512)),
                ('phone', models.CharField(max_length=11)),
                ('title', models.CharField(choices=[('Mr.', 'Male'), ('Ms.', 'Female')], max_length=256)),
                ('email', models.EmailField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name of Restaurant')),
                ('description', models.TextField(max_length=1024, verbose_name='Restaurant description')),
                ('cuisine', models.TextField(verbose_name='type of food')),
                ('max_seats', models.PositiveIntegerField(verbose_name='Seats available')),
                ('ballroom', models.BooleanField(verbose_name='Has wedding ballroom')),
                ('has_parking', models.BooleanField(verbose_name='Restaurant parking')),
                ('price_range', models.IntegerField(default=0)),
                ('rating', models.IntegerField(verbose_name='customer rating')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
    ]
