# Generated by Django 3.0.8 on 2020-07-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200707_1821'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(max_length=1024, verbose_name='Restaurant description')),
                ('price_range', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('rating', models.IntegerField(verbose_name='customer rating')),
                ('dance_type', models.TextField(choices=[('BALLET', 'Ballet'), ('TAP', 'Tap'), ('JAZZ', 'Jazz'), ('MODERN', 'Modern'), ('LYRICAL', 'Lyrical'), ('HIP_HOP', 'Hip Hop'), ('CONTEMPORARY', 'Contemporary'), ('FOLK', 'Folk')])),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ContactPerson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Florist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(max_length=1024, verbose_name='Restaurant description')),
                ('price_range', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('rating', models.IntegerField(verbose_name='customer rating')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ContactPerson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(max_length=1024, verbose_name='Restaurant description')),
                ('price_range', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('rating', models.IntegerField(verbose_name='customer rating')),
                ('musician', models.CharField(choices=[('BAND', 'Band'), ('DJ', 'Dj'), ('SINGER', 'Singer'), ('ORCHESTRA', 'Orchestra'), ('PIANIST', 'Pianist'), ('VIOLONIST', 'Violonist'), ('PERCUSSIONIST', 'Percussionist'), ('OTHER', 'Other')], max_length=512)),
                ('genre', models.CharField(choices=[('ROCK', 'Rock'), ('POP', 'Pop'), ('HIP HOP', 'Hip hop'), ('MANELE', 'Manele'), ('EDM', 'EDM'), ('CLASSICAL', 'Classical'), ('BLUES', 'Blues'), ('JAZZ', 'Jazz'), ('RNB', 'RnB'), ('FOLK', 'Folk'), ('INDIE', 'Indie'), ('OTHER', 'Other')], max_length=512)),
                ('musician_num', models.IntegerField(default=1, verbose_name='Number of musicians')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ContactPerson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ContactPerson',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='contact_person',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.ContactPerson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='has_food_sample',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_chain',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
