# Generated by Django 3.0.8 on 2020-07-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Male'), ('Ms.', 'Female')], default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='first_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='last_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
